USE [master]
GO

/****** Object:  Database [CARRENTAL]    Script Date: 20.12.2017 17:13:03 ******/
CREATE DATABASE [CARRENTAL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CARRENTAL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\CARRENTAL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CARRENTAL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\CARRENTAL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CARRENTAL] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CARRENTAL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CARRENTAL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CARRENTAL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CARRENTAL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CARRENTAL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CARRENTAL] SET ARITHABORT OFF 
GO

ALTER DATABASE [CARRENTAL] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CARRENTAL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CARRENTAL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CARRENTAL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CARRENTAL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CARRENTAL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CARRENTAL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CARRENTAL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CARRENTAL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CARRENTAL] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CARRENTAL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CARRENTAL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CARRENTAL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CARRENTAL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CARRENTAL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CARRENTAL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CARRENTAL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CARRENTAL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CARRENTAL] SET  MULTI_USER 
GO

ALTER DATABASE [CARRENTAL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CARRENTAL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CARRENTAL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CARRENTAL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CARRENTAL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CARRENTAL] SET QUERY_STORE = OFF
GO

USE [CARRENTAL]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CARRENTAL] SET  READ_WRITE 
GO

